spring.application.name=Ejercicio12-Sistema-Monitoreo

spring.datasource.url=jdbc:postgresql://dpg-d7tj5bt0lvsc73ejdui0-a.oregon-postgres.render.com:5432/loghub
spring.datasource.username=loghub_user
spring.datasource.password=Pjt1lyQfm7ByeND1iTO45ihzeV7y1gvt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never
server.error.include-message=always

server.port=8080